 become: true
  tasks:
   - name: Install Apache
     apt:
      name: apache2
      state: present

- hosts: 172.31.46.51
  become: true
  tasks:
   - name: install PHP module for Apache
     apt:
      name: libapache2-mod-php5.6
      state: present

- hosts: 172.31.43.56
  become: true
  tasks:
  - name: start apache
    service:
     name: apache2
     state: restarted
     enabled: yes

- hosts: 172.31.43.56
  become: true
  tasks:
   - name: copy web application to the  directory
     copy:
      src: /home/ubuntu/hello.php
      dest: /var/www/html/hello.php
      mode: 0664

- hosts: 172.31.43.56
  become: true
  tasks:
  - name: check url response of managed nodel1
    uri:
     url: http://172.31.43.56
     status: 201
                                                                                                   
